################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_crypto.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_find_message.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_balance.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_message.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_output.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_tips.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_info.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_message_builder.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_outputs_from_address.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_response_error.c \
/Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_send_message.c 

OBJS += \
./Application/Tests/test_crypto.o \
./Application/Tests/test_find_message.o \
./Application/Tests/test_get_balance.o \
./Application/Tests/test_get_message.o \
./Application/Tests/test_get_output.o \
./Application/Tests/test_get_tips.o \
./Application/Tests/test_info.o \
./Application/Tests/test_message_builder.o \
./Application/Tests/test_outputs_from_address.o \
./Application/Tests/test_response_error.o \
./Application/Tests/test_send_message.o 

C_DEPS += \
./Application/Tests/test_crypto.d \
./Application/Tests/test_find_message.d \
./Application/Tests/test_get_balance.d \
./Application/Tests/test_get_message.d \
./Application/Tests/test_get_output.d \
./Application/Tests/test_get_tips.d \
./Application/Tests/test_info.d \
./Application/Tests/test_message_builder.d \
./Application/Tests/test_outputs_from_address.d \
./Application/Tests/test_response_error.d \
./Application/Tests/test_send_message.d 


# Each subdirectory must supply rules for building sources it contributes
Application/Tests/test_crypto.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_crypto.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_find_message.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_find_message.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_get_balance.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_balance.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_get_message.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_message.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_get_output.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_output.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_get_tips.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_get_tips.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_info.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_info.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_message_builder.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_message_builder.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_outputs_from_address.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_outputs_from_address.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_response_error.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_response_error.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/Tests/test_send_message.o: /Users/cyril/Documents/work/SDK/STM32CubeExpansion_IOTA1_V2.0.0/Projects/B-L4S5I-IOT01A/Applications/IOTA-Client/Src/Tests/test_send_message.c Application/Tests/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_WIFI -D__BYTE_ORDER__=__ORDER_LITTLE_ENDIAN__ '-DMBEDTLS_CONFIG_FILE=<mbedtls_config.h>' -DSTM32L4S5xx -DCRYPTO_USE_SODIUM -c -I../../Inc -I../../Inc/Time -I../../Inc/Tests -I../../Inc/Utils -I../../Inc/Wallet -I../../../../../../Drivers/BSP/B-L475E-IOT01 -I../../../../../../Drivers/BSP/Components/es_wifi -I../../../../../../Drivers/BSP/Components/vl53l0x -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/CMSIS/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Middlewares/ST/STM32_Connect_Library/Includes -I../../../../../../Middlewares/Third_Party/cJSON -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../Middlewares/Third_Party/IOTA_C/client -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api -I../../../../../../Middlewares/Third_Party/IOTA_C/client/api/v1 -I../../../../../../Middlewares/Third_Party/IOTA_C/client/network -I../../../../../../Middlewares/Third_Party/IOTA_C/core -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/inputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/outputs -I../../../../../../Middlewares/Third_Party/IOTA_C/core/models/payloads -I../../../../../../Middlewares/Third_Party/IOTA_C/core/utils -I../../../../../../Middlewares/Third_Party/IOTA_C/crypto -I../../../../../../Middlewares/Third_Party/IOTA_C/wallet -I../../../../../../Middlewares/Third_Party/libsodium/include -I../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../Middlewares/Third_Party/tinyhttp -I../../../../../../Middlewares/Third_Party/Unity -I../../../../../../Middlewares/Third_Party/uthash -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

