//
// Created by Cyril on 24/09/2021.
//

#ifndef VERTICES_STM32CUBE_PROJECTS_B_L4S5I_IOT01A_APPLICATIONS_VERTICES_CLIENT_INCLUDE_UTILS_CREDENTIALS_H
#define VERTICES_STM32CUBE_PROJECTS_B_L4S5I_IOT01A_APPLICATIONS_VERTICES_CLIENT_INCLUDE_UTILS_CREDENTIALS_H

#include <net_address.h>

#ifndef CONFIG_WIFI_SSID
#define CONFIG_WIFI_SSID    ""
#warning "Please define CONFIG_WIFI_SSID"
#endif

#ifndef CONFIG_WIFI_PSK
#define CONFIG_WIFI_PSK     ""
#warning "Please define CONFIG_WIFI_PSK"
#endif

int32_t
set_network_credentials(net_if_handle_t *pnetif);

#endif //VERTICES_STM32CUBE_PROJECTS_B_L4S5I_IOT01A_APPLICATIONS_VERTICES_CLIENT_INCLUDE_UTILS_CREDENTIALS_H
